name       : haskell-dbus
version    : 1.0.1
release    : 2
source     :
    - http://hackage.haskell.org/package/dbus-1.0.1/dbus-1.0.1.tar.gz : a325b5c6958a343b30fd378d54ac01f9db889a4d7cadb14b2103da7ef4e7e8f5
license    : GPL-3.0
component  : programming.haskell
summary    : This library is an implementation of the D-Bus protocol in Haskell. It can be used to add D-Bus support to Haskell applications, without the awkward interfaces common to foreign bindings.
description: |
    This library is an implementation of the D-Bus protocol in Haskell. It can be used to add D-Bus support to Haskell applications, without the awkward interfaces common to foreign bindings.
builddeps  :
    - haskell-cabal-install
    - haskell-cereal
    - haskell-lens
    - haskell-libxml-sax
    - haskell-network
    - haskell-parsec
    - haskell-random
    - haskell-split
    - haskell-th-lift
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
